web:
    build: .
    volumes:
        - ".:/src/app"
    ports:
        - "3000:3000"
    links:
        - "db:mysql"

db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: "agility-notebook"
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    volumes:
        - "db_volume:/var/lib/mysql"
